homework #8 terraform-1
Otus-DevOps-2018-11/gitarrissima_infra pull request #5
Opened 2019-02-05 23:56 UTC by gitarrissima

# Выполнено ДЗ № 8

 - [*] Основное ДЗ
 - [*] Задание со *

## В процессе сделано

1. установила terraform                                                                                                                                                                                                                                                 2. написала и проверила выполнение кода создания виртуальной машины                                                                    на основе image = reddit-base как было показано в основной части ДЗ                                                                                                                                                                                                  3. научилась использовать утилиту terraform c ключами plan, apply, show                                                                определять входные переменные, задавать им дефолтные значения                                                                       задавать правила парсинга output команды terraform apply в выходные переменные                                                      использовать provisioners                                                                                                                                                                                                                                            4. выполнила самостоятельные задания:                                                                                                  - определила input переменную для приватного ключа                                                                                    использующегося в определении подключения для провижинеров                                                                        - пределила input переменную для задания зоны в ресурсе                                                                               "google_compute_instance" "app". Задала значение по умолчанию                                                                     - отформатировала все конигурационные файлы                                                                                         - добавила несколько ssh ключей для разворачиваемого образа                                                                         - в файле terraform/lb/lf.tf описала создание HTTP балансировщика                                                                     на основе образа reddit-full из предыдущей домашней работы                                                                        - вынесла определение количества инстансов в переменную count                                                                         с дефолтным значением = 1
--

## PR checklist
 - [*] Выставил label с номером домашнего задания
 - [*] Выставил label с темой домашнего задания

2019-02-06 05:50 UTC, mrgreyves requested changes
Здравствуйте!) Постарайтесь починить тесты. Пока возвращаю на доработку =)

2019-02-07 21:49 UTC, gitarrissima commented
пользователя назвала test. переименовать чтобы тесты прошли или и так нормально?

2019-02-11 15:16 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/52572511-055c9080-2e29-11e9-8283-54c92c295dd2.png)
Проблема тут несколько в другом, пытается запуститься terraform validate и использовать файл переменных terraform.tfvars.example, а его в репозитории нет. Так же у вас скопился "мусор" в папке packer. Думаю если навести порядок все должно быть хорошо =)

2019-02-12 07:49 UTC, mrgreyves requested changes
Все еще возвращаю на доработку, наведите порядок в директориях.

2019-03-10 19:39 UTC, gitarrissima commented
не прошло и месяца) извиняюсь за задержку. я не то, чтобы не знала, просто руки не доходили до домашних заданий.

2019-03-11 05:39 UTC, mrgreyves commented
Здравствуйте!) И такое тоже бывает, хорошо что вы снова взялись за домашки =)

2019-03-11 05:43 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил еще раз, апрув!=)

2019-03-11 18:21 UTC, merged